### ISSUE TITLE
Bug // Compress Spooler will no longer drop messages

### ISSUE THREAD

**Issue by Bradox** [logstash-plugins/logstash-codec-compress_spooler#3]
Issue https://github.com/elasticsearch/logstash-contrib/pull/111 is still present

**Comment by theflimflam** [comment]
What would it take to get this PR merged?

**Comment by theflimflam** [comment]
Quoting from elastic/logstash-contrib#111, when the last message is ready to be spooled, compressed spooler will drop the message it's currently processing and push out the spool. If your spool size is 10, this means on the 11th message it will send that spool.

This changes the logic to add the message to the spool, and then immediately send it if it's the right size.

**Comment by purbon** [comment]
Fixed in #7
